name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download go-langserver
      run: go get -u github.com/sourcegraph/go-langserver

    - name: Build go-langserver
      run: ${{ format('go build -o go-langserver_{0} "github.com/sourcegraph/go-langserver"', runner.os ) }} 

    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ format('go-langserver{0}', github.sha)}}
        release_name: ${{ format('go-langserver{0}', github.sha)}}
        draft: false
        prerelease: false
        allow_override: true
    - name: Upload Linux build
      if: ${{ runner.os == 'Linux' }}
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ format('./go-langserver_{0}', runner.os ) }} 
        asset_name: ${{ format('go-langserver_{0}', runner.os ) }} 
        asset_content_type: application/octet-stream
